name: python-docker-trivy

on:
    push:
        branches:
            - main
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Debug Docker Hub username
              run: echo "Docker Hub username is ${{ vars.DOCKERHUB_USERNAME }}, sec is  == ${{ secrets.DOCKERHUB_TOKEN }} "
              
            -
                name: login to docker hub
                uses: docker/login-action@v3
                with:
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
                    username: ${{ vars.DOCKERHUB_USERNAME }}
            -
                name: build dev
                uses: docker/build-push-action@v6
                with:
                    file: ./dockerfile.dev
                    push: true
                    tags: user/app:dev


